"""create mailbox and message tables

Revision ID: 82749045f890
Revises: 
Create Date: 2026-06-07 09:09:21.859119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82749045f890'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_extended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_mailbox_expires_at'), 'mailbox', ['expires_at'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailbox.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_mailbox_id'), 'message', ['mailbox_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_mailbox_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_mailbox_expires_at'), table_name='mailbox')
    op.drop_table('mailbox')
    # ### end Alembic commands ###
